### ISSUE TITLE
Can't make it to work on fly.io

### ISSUE THREAD

**Issue by AlonGvili** [itsMapleLeaf/remix-tailwind#3]
on dev mode in my local env everything working great but when deployed to fly.io I get an error that the mime type is text/html and not text/css even if I set the type attribute on the exported link to text/css it doesn't  work

btw I'm using custom CSS file

**Comment by itsMapleLeaf** [comment]
Can you show your code, or provide a minimal reproduction for this?

**Comment by AlonGvili** [comment]
> Can you show your code, or provide a minimal reproduction for this?

i just copy your example from the custom CSS section and point it to my CSS file
```
// app/routes/tailwindcss.tsx
import type { LoaderFunction } from "remix"
import { serveTailwindCss } from "remix-tailwind"

export const loader: LoaderFunction = () => serveTailwindCss("app/tailwind.css")
```

 my custom CSS file
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .animation-delay-2000 {
    animation-delay: 2s;
  }
  .animation-delay-4000 {
    animation-delay: 4s;
  }
  .animation-delay-3000 {
    animation-delay: 3s;
  }
}
```
